### ISSUE TITLE
how to export 3d file?

### ISSUE THREAD

**Issue by yaojinzhen** [alexzhou907/DreamPropeller#3]
Hi, I successfully ran the _launch_speedup.py_ file for training, but when I tried to export a 3D file by changing **-- train** to **-- export**, I found that the program could not run. I carefully checked the _launch_speedup.py_ and _launch_baseline.py_ in the project and found that there were **export** parameters inside, but never used. When I tried to export 3D files using _launch. py_ in threshtudio, I found it to be incompatible with this project. So how can I export 3D files, or does the project not provide this function?

**Comment by alexzhou907** [comment]
Sorry for the delay! You are correct I did not implement export 3D files. I only checked correctness of visualizing via video. If you manage to figure out how to export 3D model, please consider submit a pull request!
